# Generated by Django 4.2.18 on 2025-03-05 15:08

from django.db import migrations, models


def populate_is_locked(apps, schema_editor):
    CustomUser = apps.get_model("groups", "CustomUser")
    CustomUser.objects.filter(is_active=False, prevent_self_unlock=True).update(
        is_locked=False, is_active=False
    )
    CustomUser.objects.filter(
        is_active=False, prevent_self_unlock=False
    ).update(is_locked=True, is_active=True)


def revert_populate_is_locked(apps, schema_editor):
    CustomUser = apps.get_model("groups", "CustomUser")
    CustomUser.objects.filter(is_locked=False, is_active=False).update(
        is_active=False, prevent_self_unlock=True
    )
    CustomUser.objects.filter(is_locked=True, is_active=True).update(
        is_active=False, prevent_self_unlock=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0023_alter_workinggroup_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="The user is locked from the system but may unlock it via password reset.",
                verbose_name="locked",
            ),
        ),
        migrations.RunPython(populate_is_locked, revert_populate_is_locked),
        migrations.RemoveField(
            model_name="customuser",
            name="prevent_self_unlock",
        ),
    ]
