# Generated by Django 4.2.24 on 2025-12-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_customuser_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinggrouptype',
            name='help_text',
            field=models.TextField(blank=True, help_text='Help text to display to users when selecting a working group from this type'),
        ),
        migrations.AddField(
            model_name='workinggrouptype',
            name='required',
            field=models.BooleanField(default=False, help_text='Indicates whether the patient is required to select a working group from this type'),
        ),
    ]
