name: trrf

volumes:
  dev_db_data:
  dev_clinicaldb_data:
  smtp4dev_data:

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - "../..:/workspaces/fast-au"
    working_dir: /workspaces/fast-au/gasr/rdrf
    depends_on:
      - db
      - clinicaldb

  db:
    image: "postgres:${POSTGRES_VERSION}"
    env_file:
      - docker/dev/envs/postgres
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    ports:
      - "18432:5432"

  clinicaldb:
    image: "postgres:${POSTGRES_VERSION}"
    env_file:
      - docker/dev/envs/postgres
    volumes:
      - dev_clinicaldb_data:/var/lib/postgresql/data
    ports:
      - "18433:5432"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    environment:
      ServerOptions__Urls: http://*:80
      ServerOptions__HostName: smtp4dev
    volumes:
      - smtp4dev_data:/smtp4dev
    ports:
      - "${SMTP4DEV_WEB_PORT:-18500}:80"
      - "${SMTP4DEV_SMTP_PORT:-18525}:25"
      - "${SMTP4DEV_IMAP_PORT:-18543}:143"

  runserver:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: ${TRRF_IMAGE_NAME}
    environment:
      ALLOWED_HOSTS: "${RUNSERVER_ALLOWED_HOSTS-127.0.0.1 localhost [::1]}"
      DJANGO_FIXTURES: "${RUNSERVER_FIXTURES-DEV}"
    env_file:
      - docker/dev/envs/postgres
      - docker/dev/envs/runserver
      - .env_local
    restart: on-failure
    volumes:
      - "${HOST_WORKSPACE_FOLDER:-.}:/app"
      - "${HOST_WORKSPACE_FOLDER:-.}/data/dev/:/data"
    ports:
      - "${TRRF_HOST_PORT:-18000}:8000"
    depends_on:
      - db
      - clinicaldb
      - smtp4dev
      # - xray-daemon

  longitudinal-followup-lambda:
    image: ${TRRF_IMAGE_NAME}
    env_file:
      - docker/dev/envs/postgres
      - docker/dev/envs/runserver
      - .env_local
    volumes:
      - "${HOST_WORKSPACE_FOLDER:-.}:/app"
      - "${HOST_WORKSPACE_FOLDER:-.}/data/dev/:/data"
    ports:
      - "18001:8080"
    depends_on:
      - db
      - clinicaldb
      - smtp4dev
      # - xray-daemon
    working_dir: /app
    command:
      - lambda_local
      - lambda.longitudinal_followup_handler

  # xray-daemon:
  #   image: amazon/aws-xray-daemon:3.2.0
  #   ports:
  #     - "2000"
  #     - "2000/udp"
  #   env_file:
  #     - .env_local
  #   command: ["-o", "--bind", "0.0.0.0:2000"]
