# Generated by Django 4.2.22 on 2025-06-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0064_patient_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='country',
            field=models.CharField(max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='date_of_migration',
            field=models.DateField(blank=True, null=True, verbose_name='Date of migration'),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Indeterminate')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='country',
            field=models.CharField(max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='date_of_migration',
            field=models.DateField(blank=True, null=True, verbose_name='Date of migration'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Indeterminate')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postcode'),
        ),
    ]
