# Generated by Django 4.2.25 on 2026-07-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0174_alter_language_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.registry')),
                ('registry_form', models.ForeignKey(help_text="The CDE form holding the instrument's questions; the form's sections are the instrument's parts", on_delete=django.db.models.deletion.CASCADE, to='rdrf.registryform')),
            ],
            options={
                'unique_together': {('registry', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PROInstrumentAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(db_index=True)),
                ('context_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_payload', models.JSONField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='rdrf.proinstrument')),
            ],
            options={
                'unique_together': {('instrument', 'patient_id', 'context_id')},
            },
        ),
        migrations.CreateModel(
            name='PROInstrumentPartState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_states', to='rdrf.proinstrumentadministration')),
            ],
            options={
                'unique_together': {('administration', 'section_code')},
            },
        ),
    ]
